// <auto-generated />
using Mazzatech.Agendamento.Domain;
using Mazzatech.Agendamento.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Mazzatech.Agendamento.Repository.Migrations
{
    [DbContext(typeof(BancoContexto))]
    [Migration("20180207220923_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Mazzatech.Agendamento.Domain.AgendamentoMedico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataConsulta");

                    b.Property<DateTime>("DataCriado");

                    b.Property<DateTime?>("DataModificado");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(400);

                    b.Property<long>("MedicoId");

                    b.Property<long>("PacienteId");

                    b.Property<int>("Status");

                    b.Property<long?>("UsuarioCriadoId");

                    b.Property<long?>("UsuarioModificadoId");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("Mazzatech.Agendamento.Domain.Medico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CRM")
                        .HasMaxLength(40);

                    b.Property<string>("Celular")
                        .HasMaxLength(16);

                    b.Property<DateTime>("DataCriado");

                    b.Property<DateTime?>("DataModificado");

                    b.Property<string>("Especialidade")
                        .HasMaxLength(300);

                    b.Property<string>("Nome")
                        .HasMaxLength(300);

                    b.Property<int>("Status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(16);

                    b.Property<long?>("UsuarioCriadoId");

                    b.Property<long?>("UsuarioModificadoId");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("Mazzatech.Agendamento.Domain.Paciente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF")
                        .HasMaxLength(14);

                    b.Property<string>("Celular")
                        .HasMaxLength(16);

                    b.Property<DateTime>("DataCriado");

                    b.Property<DateTime?>("DataModificado");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150);

                    b.Property<string>("EnderecoCompleto")
                        .HasMaxLength(300);

                    b.Property<string>("Nome")
                        .HasMaxLength(300);

                    b.Property<int>("Status");

                    b.Property<string>("Telefone")
                        .HasMaxLength(16);

                    b.Property<long?>("UsuarioCriadoId");

                    b.Property<long?>("UsuarioModificadoId");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("Mazzatech.Agendamento.Domain.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriado");

                    b.Property<DateTime?>("DataModificado");

                    b.Property<string>("Login")
                        .HasMaxLength(50);

                    b.Property<string>("Nome")
                        .HasMaxLength(300);

                    b.Property<string>("Senha")
                        .HasMaxLength(150);

                    b.Property<int>("Status");

                    b.Property<long?>("UsuarioCriadoId");

                    b.Property<long?>("UsuarioModificadoId");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Mazzatech.Agendamento.Domain.AgendamentoMedico", b =>
                {
                    b.HasOne("Mazzatech.Agendamento.Domain.Medico", "Medico")
                        .WithMany("Agendamentos")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Mazzatech.Agendamento.Domain.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
